// TypeScript/每日作业/vue应用ts/Day-01/shoppingCart/src/components/CartTotal/index.vue
<template>
  <div class="total">
    <span>总价：{{totalPrices}}</span>
    <button>结算</button>
  </div>
</template>

<script lang="ts">
// defineComponent 使ts正确推断 Vue 组件选项中的类型
import { defineComponent } from "vue";

export default defineComponent({
  props:{
    list:{
      type:Array,
      required:true
    }
  },
  computed:{
    // 总价
    totalPrices(){
      let sum = 0;
      this.list.forEach(ele => {
        sum += ele.num * ele.price
      });
      return sum;
    }
  }
});
</script>

<style>
</style>

// React/每日作业/2021.05.11/cart-case/src/components/CartTotal/index.jsx
import React, { Fragment } from 'react';

class CartTotal extends React.Component {
    handleTotalPrice = ()=>{
        // 遍历求和
        let sum = 0;
        this.props.fczlist.forEach(item => {
            sum += item.price * item.num
        });
        return sum;
    }
    render() {
        return (
            <Fragment>
                <div className="total">
                    <span>总价：{this.handleTotalPrice()}</span>
                    <button>结算</button>
                </div>
            </Fragment>
        )
    }
}

export default CartTotal;
