// React/每日作业/2021.06.16/cart-Hooks-case/src/components/CartTotal/index.jsx
import React, { Fragment } from 'react';

function CartTotal(props) {
    const handleTotalPrice = () => {
        // 遍历求和
        let sum = 0;
        props.fczlist.forEach(item => {
            sum += item.price * item.num
        });
        return sum;
    }
    return (
        <Fragment>
            <div className="total">
                <span>总价：{handleTotalPrice()}</span>
                <button>结算</button>
            </div>
        </Fragment>
    )
}

export default CartTotal;

// TypeScript/每日作业/vue应用ts/Day-01/shoppingCart-composition/src/components/CartTotal/index.vue
<template>
  <div class="total">
    <span>总价：{{totalPrices}}</span>
    <button>结算</button>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import "../../types/index"
export default defineComponent({
  props: {
    list:{
      type: Array,
      required: true,
    }
  },
 setup(props){
   const {list} = props;
   const totalPrices = computed(()=>{
      let sum = 0;
      list.forEach((ele:Iist) => {
        sum += ele.num * ele.price
      });
      return sum;
   })


   return{
     // 总价
     totalPrices
   }
 }
})
</script>

<style scoped>

</style>
