// React/每日作业/2021.06.16/cart-Hooks-case/src/components/CartList/index.jsx
import React, { Fragment } from 'react';

function CartList(props) {
    //#region 输入值
    const handleChange = (id, e) => {
        // console.log(id, e.target.value);
        let val = +e.target.value
        if (val < 0 || isNaN(val)) {
            val = 0
        }
        props.zcfChange(id, val)
    }
    //#endregion
    return (
        <Fragment>
            <div>
                {
                    props.fczlist.map(item => (
                        <div className="item" key={item.id}>
                            <img src={item.img} alt="" />
                            <div className="name">{item.name}</div>
                            <div className="change">
                                <a href="#!" onClick={() => props.zcfminus(item.id)}>－</a>
                                <input type="text" className="num" value={item.num} onChange={(e) => handleChange(item.id, e)} />
                                <a href="#!" onClick={() => props.zcfadd(item.id)}>＋</a>
                            </div>
                            <div className="del" onClick={() => props.zcfdel(item.id)}>×</div>
                        </div>
                    ))
                }
            </div>
        </Fragment>
    )
}

export default CartList;

// TypeScript/每日作业/vue应用ts/Day-01/shoppingCart-composition/src/components/CartList/index.vue
<template>
  <div>
    <div class="item" v-for="item in list" :key="item.id">
      <img :src="item.img" />
      <div class="name">{{ item.name }}</div>
      <div class="change">
        <a href="" @click.prevent="sub(item.id)">－</a>
        <input
          type="text"
          class="num"
          :value="item.num"
          @change="change(item.id, $event)"
        />
        <a href="" @click.prevent="add(item.id)">＋</a>
      </div>
      <div class="del" @click.prevent="del(item.id)">×</div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  props: {
    list: {
      type: Array,
      required: true,
    },
  },
  setup(props, { emit }) {
    // 数量++
    function add(id) {
      emit("change-num", {
        id: id,
        type: "add",
      });
    }
    // 数量++
    function sub(id) {
      emit("change-num", {
        id: id,
        type: "sub",
      });
    }
    // 输入改变数量
    function change(id, e) {
      // 非负处理
      if (e.target.value < 0) e.target.value = 0;
      emit("change-num", {
        id: id,
        type: "change",
        num: e.target.value,
      });
    }
    // 删除
    function del(id) {
      emit("change-num", {
        id: id,
        type: "del",
      });
    }

    return {
      add,
      sub,
      change,
      del
    };
  },
});
</script>

<style scoped>
</style>
